[project]
name = "filter-high-frequency-traders-from-from-apexliquid"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
    "retry>=0.9.2",
]

[tool.uv]
venv = ".venv"
